service: croupon-serverless

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.constant.REGION}

custom:
  constant: ${file(env.yml):CONSTANT}
  environment: ${file(env.yml):${opt:stage}}

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/iam-policies.yml)}

functions:
  - ${file(src/api/controllers/users/functions.yml)}
  - ${file(src/api/controllers/coupons/functions.yml)}
